#!/usr/bin/env bash

if [ -n "$AWS_BUCKET" ]; then
  touch .s3cfg
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
#comment out this:  s3cmd ls s3://${AWS_BUCKET}
  if [ -d ${MINECRAFT_WORLD_NAME} ]; then
    echo "Syncing World Name: " ${MINECRAFT_WORLD_NAME}
    s3cmd sync ${MINECRAFT_WORLD_NAME}/ s3://${AWS_BUCKET}/${MINECRAFT_WORLD_NAME}/
    echo "Syncing Plugins"
    s3cmd sync plugins/ s3://${AWS_BUCKET}/${PLUGIN_DIRECTORY}/
    for entry in ${PLUGIN_DIRECTORY}/*
    do
        echo "$entry"
    done
  else
    echo "Copying World"
    mkdir -p ${MINECRAFT_WORLD_NAME}
    cd ${MINECRAFT_WORLD_NAME}
    s3cmd get --recursive s3://${AWS_BUCKET}/$MINECRAFT_WORLD_NAME/
    cd ..
  fi
  rm .s3cfg
fi
