#!/usr/bin/env bash

if [ -n "$AWS_BUCKET" ]; then
  touch .s3cfg
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  
  # This section tries to sync the world from storage on AMAZON
  if [ -d ${MINECRAFT_WORLD_NAME} ]; then
    echo "Syncing World Name: " ${MINECRAFT_WORLD_NAME}
    s3cmd sync ${MINECRAFT_WORLD_NAME}/ s3://${AWS_BUCKET}/${MINECRAFT_WORLD_NAME}/
  else
    echo "Copying World: " ${MINECRAFT_WORLD_NAME}
    mkdir -p ${MINECRAFT_WORLD_NAME}
    cd ${MINECRAFT_WORLD_NAME}
    s3cmd get --recursive s3://${AWS_BUCKET}/$MINECRAFT_WORLD_NAME/
    cd ..
  fi
  
  # This section tries to copy the plugin data from storage on AMAZON
  echo "Syncing Plugins:"
  s3cmd ls s3://${AWS_BUCKET}/${PLUGIN_DIRECTORY}/
  
  # tried to sync with this, but its failing.. s3cmd sync ${PLUGIN_DIRECTORY}/ s3://${AWS_BUCKET}/${PLUGIN_DIRECTORY}/
  mkdir -p ${PLUGIN_DIRECTORY}
  cd ${PLUGIN_DIRECTORY}
  s3cmd get --recursive s3://${AWS_BUCKET}/$PLUGIN_DIRECTORY/
  cd ..
  for entry in ${PLUGIN_DIRECTORY}/*
  do
    echo "$entry"
  done
  
  rm .s3cfg
fi
